logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG

spring:
  profiles:
    active: dev
claimsassist:
  plivoproperty:
    authId:
    authtoken:
    answerUrl: http://139.59.85.157:8080/getCallResponse
    callerNo: +919108821881
  xlsfilesproperty:
    empContactPath : /swara/
    accountClaimsPath : /swara/